/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BundleRouteImport } from './routes/bundle'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as UpsellSlugRouteImport } from './routes/upsell.$slug'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BundleRoute = BundleRouteImport.update({
  id: '/bundle',
  path: '/bundle',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const UpsellSlugRoute = UpsellSlugRouteImport.update({
  id: '/upsell/$slug',
  path: '/upsell/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bundle': typeof BundleRoute
  '/checkout': typeof CheckoutRoute
  '/library': typeof LibraryRoute
  '/thank-you': typeof ThankYouRoute
  '/upsell/$slug': typeof UpsellSlugRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bundle': typeof BundleRoute
  '/checkout': typeof CheckoutRoute
  '/library': typeof LibraryRoute
  '/thank-you': typeof ThankYouRoute
  '/upsell/$slug': typeof UpsellSlugRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bundle': typeof BundleRoute
  '/checkout': typeof CheckoutRoute
  '/library': typeof LibraryRoute
  '/thank-you': typeof ThankYouRoute
  '/upsell/$slug': typeof UpsellSlugRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bundle'
    | '/checkout'
    | '/library'
    | '/thank-you'
    | '/upsell/$slug'
    | '/api/public/stripe-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bundle'
    | '/checkout'
    | '/library'
    | '/thank-you'
    | '/upsell/$slug'
    | '/api/public/stripe-webhook'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/bundle'
    | '/checkout'
    | '/library'
    | '/thank-you'
    | '/upsell/$slug'
    | '/api/public/stripe-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BundleRoute: typeof BundleRoute
  CheckoutRoute: typeof CheckoutRoute
  LibraryRoute: typeof LibraryRoute
  ThankYouRoute: typeof ThankYouRoute
  UpsellSlugRoute: typeof UpsellSlugRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundle': {
      id: '/bundle'
      path: '/bundle'
      fullPath: '/bundle'
      preLoaderRoute: typeof BundleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upsell/$slug': {
      id: '/upsell/$slug'
      path: '/upsell/$slug'
      fullPath: '/upsell/$slug'
      preLoaderRoute: typeof UpsellSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BundleRoute: BundleRoute,
  CheckoutRoute: CheckoutRoute,
  LibraryRoute: LibraryRoute,
  ThankYouRoute: ThankYouRoute,
  UpsellSlugRoute: UpsellSlugRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
